version: '3'
services:
  web:
    image: nginx
    ports:
    - "8080:80"
    volumes:
    - ./webui:/usr/share/nginx/html:ro
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.2
    expose:
    - 9200
    ports:
    - "9200:9200"
# https://www.elastic.co/guide/en/elasticsearch/reference/6.4/docker.html
#  volumes:
#  - ./esdata1:/usr/share/elasticsearch/data    
  kibana:
    image: docker.elastic.co/kibana/kibana:6.4.2
    links:
    - "elasticsearch"
    ports:
    - "5601:5601"
