name: OpenEdgeOps
run-name: ${{ github.actor }} is compiling our Sample App 🚀
on: [push]
jobs:
  compile:
    name: OpenEdge Compile job
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - run: sh gradlew clean build
        working-directory: ./SportsApp/Sports        
      
  
    
