name: OpenEdgeOps
run-name: ${{ github.actor }} is compiling our Sample App 🚀
on: [push]
jobs:
  compile:
    name: OpenEdge Compile job
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - run: sh gradlew clean build
        working-directory: ./SportsApp    
      - name: upload zip file to nexus
        run: curl -v -k -u admin:${{secrets.DOCKER_PWD}} --upload-file ./build/distributions/sportsApp.tar.gz https://ec2-54-80-142-101.compute-1.amazonaws.com:8443/repository/PugChallengeMaven/com/progess/sportsapp/1.0.0/sportsapp-1.0.0.tar.gz
        working-directory: ./SportsApp
  deploy:
    name: Sample App Deploy
    runs-on: self-hosted
    steps:
      - name: Download the application artifact
        run: pwd && wget https://ec2-54-80-142-101.compute-1.amazonaws.com:8443/repository/PugChallengeMaven/com/progess/sportsapp/1.0.0/sportsapp-1.0.0.tar.gz --no-check-certificate
      - name: Extract the artifact
        run: tar -zxf sportsapp-1.0.0.tar.gz
      - name: Download the OpenEdge License file
        run: wget -cO - https://ec2-54-80-142-101.compute-1.amazonaws.com:8443/repository/PugChallengeMaven/OpenEdge/linux/12.8.0/linux-12.8.0-license.cfg > progress.cfg --no-check-certificate


      
  
    
