name: OpenEdgeOps
run-name: ${{ github.actor }} is compiling our Sample App 🚀
on: [push]
jobs:
  compile:
    name: OpenEdge Compile job
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - run: sh gradlew clean build
        working-directory: ./SportsApp/Sports    
      - name: Nexus Repo Publish
        uses: sonatype-nexus-community/nexus-repo-github-action@master
        with:
          serverUrl: https://ec2-54-80-142-101.compute-1.amazonaws.com:8443
          username: admin
          password: Progress2023!
          format: maven2
          repository: PugChallengeMaven
          coordinates: groupId=com.progress artifactId=sportsapp version=1.0.0
          assets: extension=oear
          filename: ./build/distribustion/Sports.oear      
      
  
    
