name: OpenEdgeOps
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  compile:
    name: OpenEdge Compile job
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - run: cd SportsApp
      - run: ./gradlew -DSTAGE_ENVIRONMENT=staging clean build
  
    
